<?php

namespace AppBundle\Repository;

/**
 * CarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRepository extends \Doctrine\ORM\EntityRepository
{
    public function getActive(){

        $qb = $this->createQueryBuilder('c'); //c gali buti car
        $qb->select('c');
        $qb->where('c.active = true');
        $qb->andWhere("c.driver = 'Mokinys'");

        return $qb->getQuery()->getResult();
    }

    public function findByDriver($driver){

        $qb = $this->createQueryBuilder('c'); //this pavadina c šitą valdymą
        $qb->
            select('c')->
            where('c.active = true')->

            andWhere($qb->expr()->like('c.driver', ':drv'))->
            //andWhere('c.driver LIKE %:drv%')-> // LIKE panašus kaip "="
            setParameter('drv', "%$driver%")
        ;

        return $qb->getQuery()->getResult();

    }
}
